// import React from "react"

// export function Layout({children}: { children: React.ReactNode }){
//     return <div> Layout {children} </div>
// }


import Head from "next/head";
import React from 'react';
// import { LaptopOutlined, NotificationOutlined, UserOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Breadcrumb, Layout as AntdLayout, Menu, theme, Dropdown, Space } from 'antd';
import styles from "./index.module.css"
import { ReadOutlined, DownOutlined } from '@ant-design/icons';
import { useRouter } from 'next/router';


const { Header, Content, Sider, Footer } = AntdLayout;

const ITEMS = [
    {
        key: 'book',
        // icon: React.createElement(icon),
        label:'图书管理',
        children: [
            { label:"图书列表", key:"/book" },
            { label:"图书添加", key:"/book/add"},
        ],
    },
    {
        key: 'borrow',
        label:'借阅管理',
        children: [
            { label:"借阅列表", key:"/borrow" },
            { label:"借阅添加", key:"/borrow/add"},
        ],
    },
    {
        key: 'category',
        label:'分类管理',
        children: [
            { label:"分类列表", key:"/category" },
            { label:"分类添加", key:"/category/add"},
        ],
    },
    {
        key: 'user',
        label:'用户管理',
        children: [
            { label:"用户列表", key:"/user" },
            { label:"用户添加", key:"/user/add"},
        ],
    },
]

const USER_ITEMS: MenuProps['items'] = [
    {
        label: "用户中心",
        key: "1",
      },
      {
        label: "登出",
        key: "2",
      },
  ];    


export function Layout({children}: { children: React.ReactNode }){
    // const {
    //     token: { colorBgContainer, borderRadiusLG },
    //   } = theme.useToken();

    const router = useRouter();
    const handleMenuClick:MenuProps["onClick"] =({key})=> {
        router.push(key);
    }

    // console.log('%c [ router ]-', 'font-size:13px; background:pink; color:#bf2c9f;', router);
    
    const activeMenu = router.pathname;


    return (
     <>
            
        <Head>
        <title>图书管理系统</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main></main>

        <AntdLayout>
            <Header className={styles.header}>
                <div className={styles.leftHeader}>
                    <ReadOutlined className={styles.logo} style={{fontSize:'32px'}}/>
                    <div className={styles.title}>图书管理系统</div>   
                </div>               
                <div className={styles.rightHeader}>
                    <Dropdown menu={{ items: USER_ITEMS }}>
                        <a onClick={(e) => e.preventDefault()}>
                        <Space>
                            用户名
                            <DownOutlined />
                        </Space>
                        </a>
                    </Dropdown>
                </div>
            </Header>

            <AntdLayout className={styles.sectionInner}>
                <Sider width={200} >
                    <Menu
                    mode="inline"
                    defaultSelectedKeys={['/book']}
                    defaultOpenKeys={['book']}
                    selectedKeys={[activeMenu]}
                    style={{ height: '100%', borderRight: 0 }}
                    items={ITEMS}
                    onClick={handleMenuClick}
                    />
                </Sider>
                <AntdLayout className={styles.sectionContent}>
                    <Content className={styles.content}>
                    {children}
                    </Content>

                    <Footer style={{ textAlign: 'center' }}>
                        Book Management System ©{new Date().getFullYear()} Created by Simon
                    </Footer>
                </AntdLayout>
                
            </AntdLayout>
            
        </AntdLayout>

     </>
    )
}