


import Head from "next/head";
import React from 'react';
import { LaptopOutlined, NotificationOutlined, UserOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { Breadcrumb, Layout as AntdLayout, Menu, theme, Dropdown, Space } from 'antd';
import styles from "./index.module.css"
import Image from 'next/image';
import { ReadOutlined, DownOutlined, SmileOutlined } from '@ant-design/icons';
import { useRouter } from 'next/router';


const { Header, Content, Sider, Footer } = AntdLayout;

const ItEMS = [
    {
        key: 'book',
        // icon: React.createElement(icon),
        label:'图书管理',
        children: [
            { label:"图书列表", key:"/book" },
            { label:"图书添加", key:"/book/add"},
        ],
    },
    {
        key: 'borrow',
        label:'借阅管理',
        children: [
            { label:"借阅列表", key:"/borrow" },
            { label:"借阅添加", key:"/borrow/add"},
        ],
    },
    {
        key: 'category',
        label:'分类管理',
        children: [
            { label:"分类列表", key:"/category" },
            { label:"分类添加", key:"/category/add"},
        ],
    },
    {
        key: 'user',
        label:'用户管理',
        children: [
            { label:"用户列表", key:"/user" },
            { label:"用户添加", key:"/user/add"},
        ],
    },
]

const USER_ITEMS: MenuProps['items'] = [
    {
        label: "用户中心",
        key: "1",
      },
      {
        label: "登出",
        key: "2",
      },
  ];    



export function Layout({children}: { children: React.ReactNode }){
    const {
        token: { colorBgContainer, borderRadiusLG },
      } = theme.useToken();

    const router = useRouter();
    const handleMenuClick =({key})=> {
        router.push(key);
    }

    return (
     <>
            
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        </main>
        






        {/*  原始设计*/}
        <AntdLayout>
            <Header className={styles.header}>
            <div className={styles.leftHeader}>
                    <ReadOutlined className={styles.logo} style={{fontSize:'32px'}}/>
                    <div className={styles.title}>图书管理系统</div>   
                </div>
                

                <div className={styles.rightHeader}>
                    <Dropdown menu={{ items: USER_ITEMS }}>
                        <a onClick={(e) => e.preventDefault()}>
                        <Space>
                            用户名
                            <DownOutlined />
                        </Space>
                        </a>
                    </Dropdown>
                </div>
            </Header>
            <Content style={{ padding: '0 48px' }}>
                <AntdLayout
                style={{ height:'calc(100vh - 130px)', padding: '24px 0', background: colorBgContainer, borderRadius: borderRadiusLG }
                }
                >
                    <Sider style={{ background: colorBgContainer }} width={200}>
                        <Menu
                        mode="inline"
                        defaultSelectedKeys={['/book']}
                        defaultOpenKeys={['book']}
                        style={{ height: '100%' }}
                        items={ItEMS}
                        onClick={handleMenuClick}
                        />
                    </Sider>
                <Content style={{ padding: '0 24px', minHeight: 280 }}> {children}</Content>
                </AntdLayout>
            </Content>
            <Footer style={{ textAlign: 'center' }}>
                Ant Design ©{new Date().getFullYear()} Created by Ant UED
            </Footer>
        </AntdLayout>
     </>
    )
}